# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: hs2048
version: '0.0.0'
github: "devankestel/hs2048"
license: MIT
author: "Devan"
maintainer: "Devan"
# synopsis: A new Haskeleton package.
# description: hs2048 is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

executables:
  hs2048:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - hs2048
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  hs2048-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - hs2048
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  hs2048-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - hs2048
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
